# -*- coding: utf-8 -*-
"""Safe project scaffolding tool for the ALI agent."""
from __future__ import annotations
from pathlib import Path
from typing import Any
from tools.base import Tool, ToolResult, ToolPermission
from security.paths import safe_project_path

TEMPLATES={
    'python': {
        'README.md':'# {name}\n\nGenerated by ALI Studio.\n',
        'main.py':'def main():\n    print("Hello from {name}")\n\nif __name__ == "__main__":\n    main()\n',
        'tests/test_main.py':'from main import main\n\ndef test_main_exists():\n    assert callable(main)\n',
    },
    'sqlite': {
        'README.md':'# {name}\n\nSQLite starter project generated by ALI.\n',
        'app.py':'import sqlite3\n\nDB="app.db"\n\ndef init_db():\n    with sqlite3.connect(DB) as con:\n        con.execute("CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY, name TEXT NOT NULL)")\n\nif __name__ == "__main__":\n    init_db()\n',
        'tests/test_app.py':'from app import init_db\n\ndef test_init_db(tmp_path, monkeypatch):\n    monkeypatch.setattr("app.DB", str(tmp_path / "test.db"))\n    init_db()\n',
    },
    'web': {
        'README.md':'# {name}\n\nMinimal standard-library web project.\n',
        'server.py':'from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler\n\nif __name__ == "__main__":\n    ThreadingHTTPServer(("127.0.0.1", 8080), SimpleHTTPRequestHandler).serve_forever()\n',
        'index.html':'<!doctype html><html><body><h1>{name}</h1><p>Generated by ALI Studio.</p></body></html>\n',
    },
}

class CreateProjectTool(Tool):
    name='create_project'
    description='Create a safe starter project inside the current workspace.'
    permission=ToolPermission.DEFAULT
    input_schema={'type':'object','properties':{'name':{'type':'string'},'template':{'type':'string','enum':list(TEMPLATES.keys())}},'required':['name','template']}
    def execute(self,ctx:Any,**kwargs)->ToolResult:
        name=str(kwargs.get('name','')).strip(); template=str(kwargs.get('template','python')).strip().lower()
        if not name or any(x in name for x in ('..','/','\\')): return ToolResult.fail('invalid project name',code='PARSE')
        if template not in TEMPLATES: return ToolResult.fail('unknown template',code='PARSE')
        try: root=safe_project_path(ctx.project_dir,name)
        except PermissionError as e: return ToolResult.fail(str(e),code='PATH_BLOCKED')
        if root.exists(): return ToolResult.fail('project already exists: '+name,code='ALREADY_EXISTS')
        try:
            for rel,content in TEMPLATES[template].items():
                p=root/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content.format(name=name),encoding='utf-8')
            return ToolResult.ok_payload(path=str(root),template=template,files=list(TEMPLATES[template]))
        except Exception as e: return ToolResult.fail(str(e),code='IO_ERROR')
